param(
    [Parameter(Position = 0)]
    [ValidateSet("prepare", "start", "stop", "status")]
    [string] $Command = "prepare",

    [string] $Config = ".\lab-10.73.json",
    [string] $ToolsRoot = "D:\tools\rpi-netboot",
    [switch] $NoDownload
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$OriginalLocation = (Get-Location).Path
if (-not [IO.Path]::IsPathRooted($Config)) {
    $Config = [IO.Path]::GetFullPath((Join-Path $OriginalLocation $Config))
}

$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

$SourcePath = Join-Path $ProjectRoot "src\RpiBootServiceLite\RpiBootServiceLite.cs"
$BinDir = Join-Path $ToolsRoot "bin"
$RunDir = Join-Path $ToolsRoot "run"
$ConfigDir = Join-Path $ToolsRoot "config"
$LogDir = "D:\logs"
$LiteExe = Join-Path $BinDir "RpiBootServiceLite.exe"
$LeasePath = Join-Path $ConfigDir "leases.tsv"
$NfsDir = Join-Path $ToolsRoot "winnfsd"
$NfsExe = Join-Path $NfsDir "WinNFSd.exe"
$NfsExports = Join-Path $ConfigDir "winnfsd-paths.txt"
$LitePidPath = Join-Path $RunDir "rpi-boot-lite.pid"
$NfsPidPath = Join-Path $RunDir "winnfsd.pid"
$WinNfsdUrl = "https://github.com/winnfsd/winnfsd/releases/download/2.4.0/WinNFSd.exe"

function Test-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Assert-Admin {
    if (-not (Test-Admin)) {
        throw "관리자 권한이 필요합니다. RPI-Netboot-Manager-Admin.exe에서 실행하세요."
    }
}

function Write-Check {
    param(
        [ValidateSet("정상", "주의", "필요", "오류")]
        [string] $Status,
        [string] $Item,
        [string] $Detail
    )
    Write-Output ("[{0}] {1} - {2}" -f $Status, $Item, $Detail)
}

function Read-ConfigObject {
    if (-not (Test-Path -LiteralPath $Config)) {
        throw "Config not found: $Config"
    }
    return Get-Content -LiteralPath $Config -Raw -Encoding UTF8 | ConvertFrom-Json
}

function Ensure-Directories {
    foreach ($path in @($ToolsRoot, $BinDir, $RunDir, $ConfigDir, $LogDir, $NfsDir)) {
        New-Item -ItemType Directory -Force -Path $path | Out-Null
    }
}

function Get-CSharpCompiler {
    $csc = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319\csc.exe"
    if (-not (Test-Path -LiteralPath $csc)) {
        $csc = Join-Path $env:WINDIR "Microsoft.NET\Framework\v4.0.30319\csc.exe"
    }
    if (-not (Test-Path -LiteralPath $csc)) {
        throw "csc.exe를 찾을 수 없습니다. .NET Framework C# compiler가 필요합니다."
    }
    return $csc
}

function Build-LiteService {
    if (-not (Test-Path -LiteralPath $SourcePath)) {
        throw "Lite service source not found: $SourcePath"
    }

    $needBuild = -not (Test-Path -LiteralPath $LiteExe)
    if (-not $needBuild) {
        $needBuild = (Get-Item -LiteralPath $SourcePath).LastWriteTimeUtc -gt (Get-Item -LiteralPath $LiteExe).LastWriteTimeUtc
    }

    if ($needBuild) {
        $csc = Get-CSharpCompiler
        & $csc /nologo /target:exe /optimize+ /platform:anycpu /codepage:65001 /out:$LiteExe $SourcePath
        if ($LASTEXITCODE -ne 0) {
            throw "RpiBootServiceLite.exe 빌드 실패"
        }
        Write-Check "정상" "내장 DHCP/TFTP 서비스 빌드" $LiteExe
    } else {
        Write-Check "정상" "내장 DHCP/TFTP 서비스" "$LiteExe 이미 준비됨"
    }
}

function Save-WinNfsd {
    if (Test-Path -LiteralPath $NfsExe) {
        Write-Check "정상" "WinNFSd" "$NfsExe 이미 준비됨"
        return
    }
    if ($NoDownload) {
        Write-Check "필요" "WinNFSd" "$NfsExe 파일이 없습니다. 다운로드가 필요합니다."
        return
    }
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $WinNfsdUrl -OutFile $NfsExe
    Write-Check "정상" "WinNFSd 다운로드" $NfsExe
}

function Write-ProviderFiles {
    $cfg = Read-ConfigObject
    Ensure-Directories

    $leaseLines = @(
        "# mac`tip`thostname`tserial"
    )
    foreach ($client in @($cfg.clients)) {
        if ($client.mac -and $client.ip) {
            $leaseLines += ("{0}`t{1}`t{2}`t{3}" -f $client.mac, $client.ip, $client.hostname, $client.serial)
        }
    }
    Set-Content -LiteralPath $LeasePath -Value $leaseLines -Encoding ASCII

    $exportLines = @(
        "# WinNFSd reference generated by RPI Netboot Manager",
        "# The start command passes these values directly because WinNFSd pathFile",
        "# parsing is strict about path and alias format.",
        "path=$($cfg.nfs_root)",
        "alias=$($cfg.nfs_alias)"
    )
    Set-Content -LiteralPath $NfsExports -Value $exportLines -Encoding ASCII

    Write-Check "정상" "Lite provider 설정" "$LeasePath, $NfsExports"
    Write-Check "정상" "예약 IP" "$(@($cfg.clients).Count)대. 현재 테스트 Pi 88:a2:9e:4f:a9:b1은 lab 설정상 10.73.0.155입니다."
}

function Stop-ProcessFromPidFile {
    param([string] $Path, [string] $Name)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Check "주의" $Name "PID 파일 없음"
        return
    }
    $pidText = (Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue).Trim()
    if (-not $pidText) {
        Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
        Write-Check "주의" $Name "PID 비어 있음"
        return
    }
    $process = Get-Process -Id ([int]$pidText) -ErrorAction SilentlyContinue
    if ($process) {
        Stop-Process -Id $process.Id -Force
        Write-Check "정상" $Name "중지됨 (PID $pidText)"
    } else {
        Write-Check "주의" $Name "PID $pidText 프로세스가 이미 없음"
    }
    Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
}

function Stop-HaneWinServices {
    foreach ($serviceName in @("DHCPservice", "TFTPService", "NFSserver", "PMAPDaemon")) {
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service -and $service.Status -ne "Stopped") {
            try {
                Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
                $service.WaitForStatus("Stopped", [TimeSpan]::FromSeconds(5))
                Write-Check "정상" $serviceName "무료 provider 포트 확보를 위해 중지"
            } catch {
                Write-Check "주의" $serviceName "서비스 중지 확인 실패: $($_.Exception.Message)"
            }
        }
    }

    foreach ($processName in @("dhcp4nt", "tftp4nt", "nfsd", "pmapd")) {
        foreach ($process in @(Get-Process -Name $processName -ErrorAction SilentlyContinue)) {
            try {
                Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
                Write-Check "정상" $processName "잔여 프로세스 중지 PID $($process.Id)"
            } catch {
                Write-Check "주의" $processName "잔여 프로세스 중지 실패 PID $($process.Id): $($_.Exception.Message)"
            }
        }
    }
}

function Get-PortOwnerSummary {
    param(
        [int[]] $TcpPorts = @(),
        [int[]] $UdpPorts = @()
    )

    $rows = @()
    foreach ($port in $TcpPorts) {
        foreach ($endpoint in @(Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue)) {
            $process = Get-Process -Id $endpoint.OwningProcess -ErrorAction SilentlyContinue
            $rows += "{0} TCP {1} PID {2} {3}" -f $endpoint.LocalAddress, $port, $endpoint.OwningProcess, $(if ($process) { $process.ProcessName } else { "unknown" })
        }
    }
    foreach ($port in $UdpPorts) {
        foreach ($endpoint in @(Get-NetUDPEndpoint -LocalPort $port -ErrorAction SilentlyContinue)) {
            $process = Get-Process -Id $endpoint.OwningProcess -ErrorAction SilentlyContinue
            $rows += "{0} UDP {1} PID {2} {3}" -f $endpoint.LocalAddress, $port, $endpoint.OwningProcess, $(if ($process) { $process.ProcessName } else { "unknown" })
        }
    }
    return $rows
}

function Add-FirewallRules {
    New-NetFirewallRule -DisplayName "RPI Netboot Lite DHCP" -Direction Inbound -Protocol UDP -LocalPort 67,68 -Action Allow -ErrorAction SilentlyContinue | Out-Null
    New-NetFirewallRule -DisplayName "RPI Netboot Lite TFTP" -Direction Inbound -Protocol UDP -LocalPort 69 -Action Allow -ErrorAction SilentlyContinue | Out-Null
    New-NetFirewallRule -DisplayName "RPI Netboot Lite NFS TCP" -Direction Inbound -Protocol TCP -LocalPort 111,2049 -Action Allow -ErrorAction SilentlyContinue | Out-Null
    New-NetFirewallRule -DisplayName "RPI Netboot Lite NFS UDP" -Direction Inbound -Protocol UDP -LocalPort 111,2049 -Action Allow -ErrorAction SilentlyContinue | Out-Null
    Write-Check "정상" "방화벽" "DHCP/TFTP/NFS lite 규칙 확인"
}

function Start-LiteProvider {
    Assert-Admin
    $cfg = Read-ConfigObject
    Ensure-Directories
    Build-LiteService
    Save-WinNfsd
    Write-ProviderFiles

    Stop-ProcessFromPidFile $LitePidPath "RpiBootServiceLite"
    Stop-ProcessFromPidFile $NfsPidPath "WinNFSd"
    Stop-HaneWinServices
    Add-FirewallRules

    $blockingOwners = @(Get-PortOwnerSummary -TcpPorts @(111, 2049) -UdpPorts @(111, 2049))
    if ($blockingOwners.Count -gt 0) {
        Write-Check "주의" "NFS 포트 사전 점검" "WinNFSd 시작 전 점유 중: $($blockingOwners -join '; ')"
    } else {
        Write-Check "정상" "NFS 포트 사전 점검" "TCP/UDP 111, 2049 비어 있음"
    }

    $serverIp = [string]$cfg.server_ip
    $routerIp = [string]$cfg.router_ip
    $dnsIp = [string]$cfg.dns_server
    if ([string]::IsNullOrWhiteSpace($dnsIp)) { $dnsIp = $routerIp }
    $tftpRoot = [string]$cfg.tftp_root
    $rootfsRoot = [string]$cfg.nfs_root
    $subnetMask = [string]$cfg.subnet_mask

    $liteStdout = Join-Path $LogDir "rpi-boot-lite.stdout.log"
    $liteStderr = Join-Path $LogDir "rpi-boot-lite.stderr.log"
    Remove-Item -LiteralPath $liteStdout, $liteStderr -Force -ErrorAction SilentlyContinue
    $liteArgs = @(
        "--leases", $LeasePath,
        "--server", $serverIp,
        "--router", $routerIp,
        "--dns", $dnsIp,
        "--subnet", $subnetMask,
        "--tftp", $tftpRoot,
        "--log", (Join-Path $LogDir "rpi-boot-lite.log"),
        "--dhcp"
    )
    $lite = Start-Process -FilePath $LiteExe -ArgumentList $liteArgs -WorkingDirectory $ProjectRoot -WindowStyle Hidden -PassThru -RedirectStandardOutput $liteStdout -RedirectStandardError $liteStderr
    Set-Content -LiteralPath $LitePidPath -Value $lite.Id -Encoding ASCII
    Write-Check "정상" "내장 DHCP/TFTP" "시작됨 PID $($lite.Id), DHCP UDP 67 / TFTP UDP 69"

    if (Test-Path -LiteralPath $NfsExe) {
        $nfsStdout = Join-Path $LogDir "winnfsd.stdout.log"
        $nfsStderr = Join-Path $LogDir "winnfsd.stderr.log"
        Remove-Item -LiteralPath $nfsStdout, $nfsStderr -Force -ErrorAction SilentlyContinue
        $nfsAlias = [string]$cfg.nfs_alias
        if ([string]::IsNullOrWhiteSpace($nfsAlias)) { $nfsAlias = "/rpi" }
        $nfsArgs = @("-addr", $serverIp, "-log", "on", $rootfsRoot, $nfsAlias)
        $nfs = Start-Process -FilePath $NfsExe -ArgumentList $nfsArgs -WorkingDirectory $NfsDir -WindowStyle Hidden -PassThru -RedirectStandardOutput $nfsStdout -RedirectStandardError $nfsStderr
        Set-Content -LiteralPath $NfsPidPath -Value $nfs.Id -Encoding ASCII
        Write-Check "정상" "WinNFSd" "시작됨 PID $($nfs.Id), $($cfg.nfs_root) -> $($cfg.nfs_alias)"
        Start-Sleep -Milliseconds 800
        $nfs.Refresh()
        if ($nfs.HasExited) {
            Write-Check "오류" "WinNFSd" "시작 직후 종료됨. 아래 로그를 확인하세요."
            foreach ($line in @(Get-Content -LiteralPath $nfsStdout -Tail 20 -ErrorAction SilentlyContinue)) { Write-Output "  stdout> $line" }
            foreach ($line in @(Get-Content -LiteralPath $nfsStderr -Tail 20 -ErrorAction SilentlyContinue)) { Write-Output "  stderr> $line" }
        }
    } else {
        Write-Check "필요" "WinNFSd" "다운로드되지 않아 NFS는 시작하지 못했습니다."
    }

    Start-Sleep -Seconds 1
    Show-LiteStatus
}

function Show-ProcessFromPidFile {
    param([string] $Path, [string] $Name)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Check "필요" $Name "실행 중 아님"
        return
    }
    $pidText = (Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue).Trim()
    $process = if ($pidText) { Get-Process -Id ([int]$pidText) -ErrorAction SilentlyContinue } else { $null }
    if ($process) {
        Write-Check "정상" $Name "실행 중 PID $pidText"
    } else {
        Write-Check "주의" $Name "PID 파일은 있지만 프로세스가 없습니다."
    }
}

function Show-LiteStatus {
    Write-Output ""
    Write-Output "== 무료 Lite provider 상태 =="
    Show-ProcessFromPidFile $LitePidPath "내장 DHCP/TFTP"
    Show-ProcessFromPidFile $NfsPidPath "WinNFSd"

    $udp67 = @(Get-NetUDPEndpoint -LocalPort 67 -ErrorAction SilentlyContinue)
    $udp69 = @(Get-NetUDPEndpoint -LocalPort 69 -ErrorAction SilentlyContinue)
    $portmapTcp = @(Get-NetTCPConnection -LocalPort 111 -ErrorAction SilentlyContinue)
    $portmapUdp = @(Get-NetUDPEndpoint -LocalPort 111 -ErrorAction SilentlyContinue)
    $tcp2049 = @(Get-NetTCPConnection -LocalPort 2049 -ErrorAction SilentlyContinue)

    if ($udp67.Count -gt 0) { Write-Check "정상" "DHCP UDP 67" (($udp67 | ForEach-Object { $_.LocalAddress }) -join ", ") } else { Write-Check "필요" "DHCP UDP 67" "대기 중 아님" }
    if ($udp69.Count -gt 0) { Write-Check "정상" "TFTP UDP 69" (($udp69 | ForEach-Object { $_.LocalAddress }) -join ", ") } else { Write-Check "필요" "TFTP UDP 69" "대기 중 아님" }
    if (($portmapTcp.Count + $portmapUdp.Count) -gt 0) { Write-Check "정상" "NFS Portmap 111" ((Get-PortOwnerSummary -TcpPorts @(111) -UdpPorts @(111)) -join "; ") } else { Write-Check "필요" "NFS Portmap 111" "대기 중 아님" }
    if ($tcp2049.Count -gt 0) { Write-Check "정상" "NFS TCP 2049" (($tcp2049 | ForEach-Object { $_.LocalAddress }) -join ", ") } else { Write-Check "필요" "NFS TCP 2049" "대기 중 아님" }

    try {
        $cfg = Read-ConfigObject
        $readyCount = 0
        $emptyCount = 0
        $missingCount = 0
        $currentClient = $null
        foreach ($client in @($cfg.clients)) {
            $clientRoot = Join-Path ([string]$cfg.nfs_root) ([string]$client.serial)
            if ($client.mac -eq "88:a2:9e:4f:a9:b1" -or $client.serial -eq "d80c0b88") {
                $currentClient = [pscustomobject]@{ Serial = $client.serial; Path = $clientRoot }
            }
            if (-not (Test-Path -LiteralPath $clientRoot)) {
                $missingCount += 1
                continue
            }
            $hasInit = (Test-Path -LiteralPath (Join-Path $clientRoot "sbin\init")) -or
                (Test-Path -LiteralPath (Join-Path $clientRoot "lib\systemd\systemd")) -or
                (Test-Path -LiteralPath (Join-Path $clientRoot "usr\lib\systemd\systemd"))
            $hasShell = (Test-Path -LiteralPath (Join-Path $clientRoot "bin\sh"))
            if ($hasInit -and $hasShell) {
                $readyCount += 1
            } elseif (@(Get-ChildItem -LiteralPath $clientRoot -Force -ErrorAction SilentlyContinue | Select-Object -First 1).Count -eq 0) {
                $emptyCount += 1
            }
        }
        Write-Check $(if ($readyCount -gt 0) { "정상" } else { "필요" }) "rootfs 준비" "$readyCount/$(@($cfg.clients).Count)대 준비됨, 빈 폴더 $emptyCount, 폴더 없음 $missingCount"
        if ($currentClient) {
            $hasCurrentInit = (Test-Path -LiteralPath (Join-Path $currentClient.Path "sbin\init")) -or
                (Test-Path -LiteralPath (Join-Path $currentClient.Path "lib\systemd\systemd")) -or
                (Test-Path -LiteralPath (Join-Path $currentClient.Path "usr\lib\systemd\systemd"))
            $hasCurrentShell = Test-Path -LiteralPath (Join-Path $currentClient.Path "bin\sh")
            if ($hasCurrentInit -and $hasCurrentShell) {
                Write-Check "정상" "현재 테스트 Pi rootfs" "$($currentClient.Path)에 init/bin/sh 있음"
            } else {
                Write-Check "필요" "현재 테스트 Pi rootfs" "$($currentClient.Path)에 sbin\init 또는 bin\sh가 없어 커널 이후 부팅 불가"
            }
        }
    } catch {
        Write-Check "주의" "rootfs 준비" "확인 실패: $($_.Exception.Message)"
    }
}

switch ($Command) {
    "prepare" {
        Ensure-Directories
        Build-LiteService
        Save-WinNfsd
        Write-ProviderFiles
        Show-LiteStatus
    }
    "start" {
        Start-LiteProvider
    }
    "stop" {
        Assert-Admin
        Stop-ProcessFromPidFile $LitePidPath "RpiBootServiceLite"
        Stop-ProcessFromPidFile $NfsPidPath "WinNFSd"
        Show-LiteStatus
    }
    "status" {
        Show-LiteStatus
    }
}




